### ISSUE TITLE
error in importing libtiff

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pearu/pylibtiff#12]
```
I am trying to use pylibtiff to read tiff files into numpy array.. i installed 
the windows installer provided on the site and now if i try importing, python 
encounters with following error:

>>> from libtiff import *

Traceback (most recent call last):
  File "D:/Python27/testtifflib.py", line 4, in <module>
    from libtiff import *
  File "D:\Python27\lib\site-packages\libtiff\__init__.py", line 4, in <module>
    from .libtiff import libtiff, TIFF
  File "D:\Python27\lib\site-packages\libtiff\libtiff.py", line 35, in <module>
    raise ImportError('Failed to find TIFF library. Make sure that libtiff is installed and its location is listed in PATH|LD_LIBRARY_PATH|..')
ImportError: Failed to find TIFF library. Make sure that libtiff is installed 
and its location is listed in PATH|LD_LIBRARY_PATH|..

i also tried this :

import sys
sys.path.append("D:\\Python27\\Lib\\site-packages\\libtiff")

from libtiff import *

but same error persists.. what can be done in this case??  any help is 
appreciated.. m i missing something here??


```

Original issue reported on code.google.com by `asmi.ca...@gmail.com` on 2 Feb 2011 at 12:35

**Comment by alice85** [comment]
Hi guys!
I had a similar problem under Windows 7: after half a day of bothering around with simply installing libtiff package (oh my!!!!) I stucked the other half of day with the PATH error, that was already mentioned on top of the present issue. My solution was quite simple - and it indeed embarrass me a little. But here is what I did:

The error is raised by libtiff_ctypes.py (originated in C:\Python27\Lib\site-packages\libtiff\), line 41 because the tiff library is not found. In line 29 you can find the location WHERE the ctypes-module is searching for the tiff library. Since I am not a friend of changing tested and in principle working python modules I copied the location path from line 29 and reinstallled the tiff package - or GnuWin32 application - into this directory. Additionally I had to add C:\Program Files\GnuWin32\bin to the PATH environment variables. For newbies: This is done by the following
Go to Control Panel -> System, on the left side click on "Advanced system settings" and enter Admin-password. Then in slide "Advanced" click on "Environment Variables" (at the bottom of the window) and in "System Variables" you search for an entry called "PATH". Here, click on "Edit" (nothing else, don't delete!!!!!!), go to the end of the line and add a semicolon and the necessary path. Confirm with "OK" etc. In principle under Windows 7 it should already work, evtl you will have to reboot the PC once

By the way: the libtiff3.dll-copy thing, recommended by Kevin, didn't work for me as well ;)

Cheers!
Alice

**Comment by pearu** [comment]
I recommend using conda libtiff.
