### ISSUE TITLE
libtiff4 vs libtiff5 & finding header.

### ISSUE THREAD

**Issue by ayjayt** [pearu/pylibtiff#124]
That error is being raised on one of my machines. It has `libtiff5-dev` installed.

https://github.com/pearu/pylibtiff/blob/51d6f2a41db654254397df1de6f9193e7317bce5/libtiff/libtiff_ctypes.py#L101

This line makes it work (I'm using `venv` where `golden-env` is my `venv` folder):
`cp /usr/include/x86_64-linux-gnu/tiff.h golden-env/include/`

More concerning, I don't get this error on at all on my local box, and I can't even find `tiff .h` with `sudo find / -name tiff.h` /shrug. Not going to really complain about something working though.

**Comment by ayjayt** [comment]
Sorry, I meant to ping @pearu  just for some visibility.

**Comment by igg** [comment]
Same here on ubuntu 20.04, fresh upgrade from 18.04. apt installed libtiff-dev, in python venv, pip install libtiff. Import libtiff in python results in tiff.h not found. copy from `/usr/include/x86_64-linux-gnu/tiff.h` to `venv/include/` fixes it.

**Comment by igg** [comment]
This works outside of a venv. The problem is that in a venv, the various search strategies (~line 66 in `libtiff_ctypes.py`) don't work (`sys.prefix` is the venv root, not for e.g. `/usr`). The deeper "problem" is that system libraries are still used in a venv. Not sure how to probe the environment outside the venv while inside a venv.

**Comment by igg** [comment]
It seems that the purpose of the search is to generate a new `tiff_h_4_1_0.py`, which is missing from the distro since it's a new version. I got it to generate by copying the tiff.h, so I leave it as a gist ([tiff_h_4_1_0.py](https://gist.github.com/igg/12faa48daf965c0cd085b47b0cd6d36b)) to include in subsequent releases.

**Comment by pearu** [comment]
https://github.com/pearu/pylibtiff/pull/130 likely fixes this issue. If not, please re-open.

**Comment by igg** [comment]
The tiff.h file is still not found when pylibtiff is installed in a venv.
The remedy is still to copy it from from the installed lib to the venv's include directory, e.g.
```cp /usr/include/x86_64-linux-gnu/tiff.h venv3-test/include/```
