### ISSUE TITLE
can't use tiff3d

### ISSUE THREAD

**Issue by unyqhz** [pearu/pylibtiff#69]
i want to read multipy tiff pictures
so I use  TIFF3D.open("test-volume.tif","r")
but something wrong:ArgumentError: argument 1: <class 'TypeError'>: wrong type

then I use img=TIFF.open("test-volume.tif"), it shows
<TIFF3D object at 0x0000021C1039A748>
but when I use  img.read_image()
another error is:
 ArgumentError: argument 3: <class 'TypeError'>: wrong type
so how can I read TIFF3D images?

thanks a lot
forgive my stupid question. And there is so little reference……

**Comment by 1995hzczjut** [comment]
I have the same question ,

**Comment by zzjjbb** [comment]
The first problem is the string must be b"/path/to/img.tiff" and b'r' . It is a problem on py3, maybe because the string are unicode by default. (I read the overrided method TIFF.open and find that they changed the encode at first, so it's right.)

I guess the second problem is also because the code is copy from a python2 project. I don't know how to change the code since I'm new to python.

Hoping the developers can finish the 2to3 work soon.

**Comment by pearu** [comment]
Fixed by PR #96.
